### ISSUE TITLE
icons would be appreciated for:

### ISSUE THREAD

**Issue by Egon370** [nandolawson/Custom-Icons-for-TwiLight-Menu#1]
wario land 1-4
donkey kong (game boy)
super mario bros + duck hunt
mario tennis: power tour
rhythm heaven silver

**Comment by Jakobowser** [comment]
Mother 1+2
(I included a sample how I would like it, so it fits with the Mother 3 icon)
![output-onlinepngtools](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/159848366/74dd1384-8a64-41d2-a8e1-b42d63da5434)

**Comment by nandolawson** [comment]
Unfortunately, I am very busy and this won't change for a few weeks. But as soon as I have some time for this, I'll work on this. 😊

**Comment by Jakobowser** [comment]
Very cool that you responded, I actually already made one that works. Thank you for your work here, I appreciate it a lot. :)
![Mother 1+2 gba](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/159848366/a2c4f1e4-1f16-4cba-a25b-6e60c6e3ff0b)

**Comment by Jakobowser** [comment]
![Mother 1+2+3_Photo_working_on_DS](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/159848366/206a23d3-52a0-4e5d-8781-c761f52f905f)
Here is it working on DS

**Comment by Jakobowser** [comment]
@Egon370 would something like this work for Wario Land?
![pixilart-drawing](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/159848366/0dc16de8-b2b8-40d6-bc57-4dac4e2074aa)

**Comment by Jakobowser** [comment]
@Egon370  how do you like this Donkey Kong icon I made?
![Donkey Kong gb](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/159848366/cd0958cf-4b92-4746-babc-176611fd39c6)

**Comment by Jakobowser** [comment]
@Egon370 the purple is a bit weird, I changed it to a blue so it fits with the boxart.
![Donkey Kong gb (2)](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/159848366/4b60881f-ab2c-443f-9c11-191aa26a70ea)

**Comment by Jakobowser** [comment]
![Donkey Kong gb](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/159848366/af81becf-124a-406d-9573-4b158c14e268)
fixed the purple stray pixels

**Comment by Jakobowser** [comment]
@Egon370 
![Rhythm Heaven Silver gba](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/159848366/66863c5b-9feb-4f95-b826-8478ded8de1f)
I made the Rhythm Heaven Silver icon you were asking for. Hope it makes you happy. :)

**Comment by Jakobowser** [comment]
![Mario Power Tennis gba](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/159848366/a16d61bb-bbe0-4cc9-b680-e4f0904d2b7e)
@Egon370

**Comment by nandolawson** [comment]
I gladly have time now to continue work on this repo. Would someone here have a problem if I add the icons above to this repo?

**Comment by Jakobowser** [comment]
Please add them, I made them for everyone to use. :)

**Comment by nandolawson** [comment]
Alright. Thank you for your contribution. 🙂

**Comment by Jakobowser** [comment]
![ef53c3b769e964a](https://github.com/user-attachments/assets/8d65b7c2-1238-4366-9b3d-4f4788eae19f)
Before you do, I made a final version for the Mother 1+2 icon.
