### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Riccardominecart** [nandolawson/Custom-Icons-for-TwiLight-Menu#3]
how can i change the icon of the game of the emulator to change it  to be the gamepad  and not to be the console
![default-md](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/151866522/ab24f84f-ad25-4076-bc4d-01def352accb)

**Comment by nandolawson** [comment]
I am unsure what you mean tbh. Can you maybe provide a photo of the icon you want changed?

**Comment by Riccardominecart** [comment]
![20240216_142625](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/151866522/b9eefa58-01d2-4468-80a9-4cda7776c34e)
This to that
![Gamepad_SEGA](https://github.com/nandolawson/Custom-Icons-for-TwiLight-Menu/assets/151866522/0031eb11-7bb5-4a00-a9f8-963ad305db7b)

**Comment by nandolawson** [comment]
You need to make a custom icon that has the same file name as the ROM. The README should contain all information you need.
